# Generated by Django 2.2.4 on 2019-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=200)),
                ('deptId', models.IntegerField()),
                ('empName', models.CharField(max_length=200)),
            ],
        ),
    ]
