# Generated by Django 2.2.4 on 2019-08-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('losal', models.IntegerField()),
                ('hisal', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='deptName',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='empName',
            new_name='loc',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='deptId',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='id',
        ),
        migrations.AddField(
            model_name='dept',
            name='deptno',
            field=models.IntegerField(default='', editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('mgr', models.IntegerField()),
                ('hiredate', models.DateTimeField(auto_now_add=True)),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormapp.dept')),
            ],
        ),
    ]
