# Generated by Django 2.2.4 on 2019-08-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_auto_20190830_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='deptno',
        ),
        migrations.DeleteModel(
            name='salgrade',
        ),
        migrations.DeleteModel(
            name='emp',
        ),
    ]
