# Generated by Django 2.2.4 on 2019-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_auto_20190830_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
