# Generated by Django 2.2.4 on 2019-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0004_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp',
        ),
    ]
